### ISSUE TITLE
Raycast isn't able to paste snippets to iterm2

### ISSUE THREAD

**Issue by dufferzafar** [raycast/snippet-explorer#40] opened 2023-06-19 15:34 UTC
I'm using iterm2 3.4.16 and have a very simply snippet defined in raycast to expand `!name` to my name

The snippet works in VS Code, Firefox, Chrome etc but not in iterm2, where the `!name` text gets removed, but nothing gets inserted.

How can I debug this further?

**Comment by peduarte** [comment] 2023-06-19 19:53
Duplicate of https://github.com/raycast/snippet-explorer/issues/38 

But also, this repo isn't the right place for this, this repo is about the Snipper Explorer web project. 

You can use the "Send Feedback" command directly in Raycast to submit issues with the app. Marcos is already working on this though 😄

**Closed by peduarte** 2023-06-19 19:53 UTC
